config/routes.rb
ShlomoApp::Application.routes.draw do

  root :to => 'pages#index'
  get "pages/company"

  get "pages/services"

  get "pages/clients"

  get "pages/news"

  get "pages/rrhh"

  get "pages/contact_us"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @title = "Index Page"
  end

  def company
    @title = "Company Page"
  end

  def services
    @title = "Services Page"
  end

  def clients
    @title = "Clients Page"
  end

  def news
    @title = "News Page"
  end

  def rrhh
    @title = "RRHH Page"
  end

  def contact_us
    @title = "Contact_us Page"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShlomoApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/clients.html.erb
<section class="container">

<title>Clients Page</title>

<h1>Clients</h1>
<header>

<nav>
<ul>
  <li><%= link_to "Company", pages_company_path %></li>
  <li><%= link_to "Services", pages_services_path %></li>
  <li><%= link_to "Clients", pages_clients_path %></li>
  <li><%= link_to "News", pages_news_path %></li>
  <li><%= link_to "RRHH", pages_rrhh_path %></li>
  <li><%= link_to "Contact_us", pages_contact_us_path %></li>
</ul>
</nav>
</header>

<section class="middle_container">
<section class="small_container">

<div id="parag">
This is the clients page.This is the clients page.This is the clients page.This is the clients page.This is the clients page.This is the clients page.
This is the clients page.This is the clients page.This is the clients page.This is the clients page.This is the clients page.This is the clients page.
This is the clients page.This is the clients page.This is the clients page.This is the clients page.This is the clients page.This is the clients page.
This is the clients page.This is the clients page.This is the clients page.This is the clients page.This is the clients page.This is the clients page.
This is the clients page.This is the clients page.This is the clients page.This is the clients page.This is the clients page.This is the clients page.
This is the clients page.This is the clients page.This is the clients page.This is the clients page.This is the clients page.This is the clients page.
This is the clients page.This is the clients page.This is the clients page.This is the clients page.This is the clients page.This is the clients page.
This is the clients page.This is the clients page.This is the clients page.This is the clients page.This is the clients page.This is the clients page.
This is the clients page.This is the clients page.This is the clients page.This is the clients page.This is the clients page.This is the clients page.
This is the clients page.This is the clients page.This is the clients page.This is the clients page.This is the clients page.This is the clients page.
This is the clients page.This is the clients page.This is the clients page.This is the clients page.This is the clients page.This is the clients page.
This is the clients page.This is the clients page.This is the clients page.This is the clients page.This is the clients page.This is the clients page.
This is the clients page.This is the clients page.This is the clients page.This is the clients page.This is the clients page.This is the clients page.
This is the clients page.This is the clients page.This is the clients page.This is the clients page.This is the clients page.This is the clients page.
</div>

</section> <!-- end of small_container -->
</section> <!-- end of middle_container -->

</section> <!-- end of container -->

app/views/pages/company.html.erb
<section class="container">

<title>Company Page</title>

<h1>Company</h1>
<header>

<nav>
<ul>
  <li><%= link_to "Company", pages_company_path %></li>
  <li><%= link_to "Services", pages_services_path %></li>
  <li><%= link_to "Clients", pages_clients_path %></li>
  <li><%= link_to "News", pages_news_path %></li>
  <li><%= link_to "RRHH", pages_rrhh_path %></li>
  <li><%= link_to "Contact_us", pages_contact_us_path %></li>
</ul>
</nav>
</header>

<section class="middle_container">
<section class="small_container">

<div id="parag">
This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.
This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.
This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.
This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.
This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.
This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.
This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.
This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.
This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.
This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.
This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.
This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.
This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.
This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.
This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.
This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.
This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.
This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.
This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.
This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.
This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.
This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.
This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.
This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.This is the company page.
</div>

</section> <!-- end of small_container -->
</section> <!-- end of middle_container -->

</section> <!-- end of container -->

app/views/pages/contact_us.html.erb
<section class="container">

<header>
<title>Contact_us Page</title>
<h1>Contact_us</h1>

<nav>
<ul>
  <li><%= link_to "Company", pages_company_path %></li>
  <li><%= link_to "Services", pages_services_path %></li>
  <li><%= link_to "Clients", pages_clients_path %></li>
  <li><%= link_to "News", pages_news_path %></li>
  <li><%= link_to "RRHH", pages_rrhh_path %></li>
  <li><%= link_to "Contact_us", pages_contact_us_path %></li>
</ul>
</nav>
</header>


<section class="middle_container">
<section class="small_container">

<div id="parag">
  This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.
  This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.
  This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.
  This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.
  This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.
  This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.
  This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.
  This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.
  This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.
  This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.
  This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.
  This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.
  This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.
  This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.
  This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.
  This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.
  This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.
  This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.
  This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.
  This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.This in the contact_us page.
</div>

</section> <!-- end of small_container -->
</section> <!-- end of middle_container -->

</section> <!-- end of container -->

app/views/pages/index.html.erb
<section class="container">

<title>Index Page</title>

<h1>Index Page</h1>
<header>

<nav>
<ul>
  <li><%= link_to "Company", pages_company_path %></li>
  <li><%= link_to "Services", pages_services_path %></li>
  <li><%= link_to "Clients", pages_clients_path %></li>
  <li><%= link_to "News", pages_news_path %></li>
  <li><%= link_to "RRHH", pages_rrhh_path %></li>
  <li><%= link_to "Contact_us", pages_contact_us_path %></li>
</ul>
</nav>
</header>

<section class="middle_container">
<section class="small_container">

<div id="parag">
This is the index page.This is the index page.This is the insdex page.This is the index page. This is the index page.This is the index page.This is the index page.
This is the index page.This is the index page.This is the insdex page.This is the index page. This is the index page.This is the index page.This is the index page.
This is the index page.This is the index page.This is the insdex page.This is the index page. This is the index page.This is the index page.This is the index page.
This is the index page.This is the index page.This is the insdex page.This is the index page. This is the index page.This is the index page.This is the index page.
This is the index page.This is the index page.This is the insdex page.This is the index page. This is the index page.This is the index page.This is the index page.
This is the index page.This is the index page.This is the insdex page.This is the index page. This is the index page.This is the index page.This is the index page.
This is the index page.This is the index page.This is the insdex page.This is the index page. This is the index page.This is the index page.This is the index page.
This is the index page.This is the index page.This is the insdex page.This is the index page. This is the index page.This is the index page.This is the index page.
This is the index page.This is the index page.This is the insdex page.This is the index page. This is the index page.This is the index page.This is the index page.
This is the index page.This is the index page.This is the insdex page.This is the index page. This is the index page.This is the index page.This is the index page.
This is the index page.This is the index page.This is the insdex page.This is the index page. This is the index page.This is the index page.This is the index page.
This is the index page.This is the index page.This is the insdex page.This is the index page. This is the index page.This is the index page.This is the index page.
This is the index page.This is the index page.This is the insdex page.This is the index page. This is the index page.This is the index page.This is the index page.
This is the index page.This is the index page.This is the insdex page.This is the index page. This is the index page.This is the index page.This is the index page.
This is the index page.This is the index page.This is the insdex page.This is the index page. This is the index page.This is the index page.This is the index page.
This is the index page.This is the index page.This is the insdex page.This is the index page. This is the index page.This is the index page.This is the index page.
This is the index page.This is the index page.This is the insdex page.This is the index page. This is the index page.This is the index page.This is the index page.
This is the index page.This is the index page.This is the insdex page.This is the index page. This is the index page.This is the index page.This is the index page.
This is the index page.This is the index page.This is the insdex page.This is the index page. This is the index page.This is the index page.This is the index page.
This is the index page.This is the index page.This is the insdex page.This is the index page. This is the index page.This is the index page.This is the index page.
This is the index page.This is the index page.This is the insdex page.This is the index page. This is the index page.This is the index page.This is the index page.
This is the index page.This is the index page.This is the insdex page.This is the index page. This is the index page.This is the index page.This is the index page.
</div>

</section> <!-- end of small_container -->
</section> <!-- end of middle_container -->

</section> <!-- end of container -->

app/views/pages/news.html.erb
<section class="container">

<title>News Page</title>

<h1>News</h1>
<header>

<nav>
<ul>
  <li><%= link_to "Company", pages_company_path %></li>
  <li><%= link_to "Services", pages_services_path %></li>
  <li><%= link_to "Clients", pages_clients_path %></li>
  <li><%= link_to "News", pages_news_path %></li>
  <li><%= link_to "RRHH", pages_rrhh_path %></li>
  <li><%= link_to "Contact_us", pages_contact_us_path %></li>
</ul>
</nav>
</header>

<section class="middle_container">
<section class="small_container">

<div id="parag">
This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.
This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.
This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.
This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.
This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.
This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.
This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.
This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.
This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.
This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.
This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.
This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.
This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.
This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.This is the news page.
</div>

</section> <!-- end of small_container -->
</section> <!-- end of middle_container -->

</section> <!-- end of container -->

app/views/pages/rrhh.html.erb
<section class="container">

<title>RRHH Page</title>

<h1>RRHH</h1>
<header>

<nav>
<ul>
  <li><%= link_to "Company", pages_company_path %></li>
  <li><%= link_to "Services", pages_services_path %></li>
  <li><%= link_to "Clients", pages_clients_path %></li>
  <li><%= link_to "News", pages_news_path %></li>
  <li><%= link_to "RRHH", pages_rrhh_path %></li>
  <li><%= link_to "Contact_us", pages_contact_us_path %></li>
</ul>
</nav>
</header>

<section class="middle_container">
<section class="small_container">

<div id="parag">
This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.
This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.
This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.
This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.
This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.
This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.
This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.
This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.
This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.
This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.This is the rrhh page.
</div>

</section> <!-- end of small_container -->
</section> <!-- end of middle_container -->

</section> <!-- end of container -->

app/views/pages/services.html.erb
<section class="container">

<title>Services Page</title>

<h1>Services</h1>
<header>

<nav>
<ul>
  <li><%= link_to "Company", pages_company_path %></li>
  <li><%= link_to "Services", pages_services_path %></li>
  <li><%= link_to "Clients", pages_clients_path %></li>
  <li><%= link_to "News", pages_news_path %></li>
  <li><%= link_to "RRHH", pages_rrhh_path %></li>
  <li><%= link_to "Contact_us", pages_contact_us_path %></li>
</ul>
</nav>
</header>

<section class="middle_container">
<section class="small_container">

<div id="parag">
This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.
This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.
This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.
This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.
This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.
This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.
This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.
This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.
This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.
This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.
This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.
This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.
This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.
This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.
This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.
This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.
This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.
This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.
This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.
This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.
This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.
This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.
This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.
This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.
This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.This is the services page.
</div>

</section> <!-- end of small_container -->
</section> <!-- end of middle_container -->

</section> <!-- end of container -->